export const POPULAR_STOCKS = [
  { symbol: 'AAPL', name: 'Apple Inc', domain: 'apple.com' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', domain: 'microsoft.com' },
  { symbol: 'GOOGL', name: 'Alphabet Inc', domain: 'google.com' },
  { symbol: 'AMZN', name: 'Amazon.com Inc', domain: 'amazon.com' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', domain: 'nvidia.com' },
  { symbol: 'META', name: 'Meta Platforms Inc', domain: 'meta.com' },
  { symbol: 'TSLA', name: 'Tesla Inc', domain: 'tesla.com' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc', domain: 'berkshirehathaway.com' },
  { symbol: 'LLY', name: 'Eli Lilly and Company', domain: 'lilly.com' },
  { symbol: 'V', name: 'Visa Inc', domain: 'visa.com' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc', domain: 'unitedhealthgroup.com' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', domain: 'exxonmobil.com' },
  { symbol: 'WMT', name: 'Walmart Inc', domain: 'walmart.com' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co', domain: 'jpmorganchase.com' },
  { symbol: 'MA', name: 'Mastercard Inc', domain: 'mastercard.com' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', domain: 'jnj.com' },
  { symbol: 'PG', name: 'Procter & Gamble Co', domain: 'pg.com' },
  { symbol: 'AVGO', name: 'Broadcom Inc', domain: 'broadcom.com' },
  { symbol: 'HD', name: 'The Home Depot Inc', domain: 'homedepot.com' },
  { symbol: 'CVX', name: 'Chevron Corporation', domain: 'chevron.com' },
  { symbol: 'MRK', name: 'Merck & Co Inc', domain: 'merck.com' },
  { symbol: 'ABBV', name: 'AbbVie Inc', domain: 'abbvie.com' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation', domain: 'costco.com' },
  { symbol: 'KO', name: 'The Coca-Cola Company', domain: 'coca-cola.com' },
  { symbol: 'PEP', name: 'PepsiCo Inc', domain: 'pepsico.com' },
  { symbol: 'ADBE', name: 'Adobe Inc', domain: 'adobe.com' },
  { symbol: 'NFLX', name: 'Netflix Inc', domain: 'netflix.com' },
  { symbol: 'CRM', name: 'Salesforce Inc', domain: 'salesforce.com' },
  { symbol: 'MCD', name: "McDonald's Corporation", domain: 'mcdonalds.com' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc', domain: 'cisco.com' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc', domain: 'thermofisher.com' },
  { symbol: 'ABT', name: 'Abbott Laboratories', domain: 'abbott.com' },
  { symbol: 'ACN', name: 'Accenture plc', domain: 'accenture.com' },
  { symbol: 'ORCL', name: 'Oracle Corporation', domain: 'oracle.com' },
  { symbol: 'NKE', name: 'NIKE Inc', domain: 'nike.com' },
  { symbol: 'DIS', name: 'The Walt Disney Company', domain: 'disney.com' },
  { symbol: 'WFC', name: 'Wells Fargo & Company', domain: 'wellsfargo.com' },
  { symbol: 'INTC', name: 'Intel Corporation', domain: 'intel.com' },
  { symbol: 'VZ', name: 'Verizon Communications Inc', domain: 'verizon.com' },
  { symbol: 'TXN', name: 'Texas Instruments Inc', domain: 'ti.com' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc', domain: 'amd.com' },
  { symbol: 'CMCSA', name: 'Comcast Corporation', domain: 'comcast.com' },
  { symbol: 'PM', name: 'Philip Morris International Inc', domain: 'pmi.com' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc', domain: 'qualcomm.com' },
  { symbol: 'HON', name: 'Honeywell International Inc', domain: 'honeywell.com' },
  { symbol: 'UNP', name: 'Union Pacific Corporation', domain: 'up.com' },
  { symbol: 'IBM', name: 'International Business Machines', domain: 'ibm.com' },
  { symbol: 'NEE', name: 'NextEra Energy Inc', domain: 'nexteraenergy.com' },
  { symbol: 'AMGN', name: 'Amgen Inc', domain: 'amgen.com' },
  { symbol: 'UPS', name: 'United Parcel Service Inc', domain: 'ups.com' },
  { symbol: 'LOW', name: "Lowe's Companies Inc", domain: 'lowes.com' },
  { symbol: 'BA', name: 'The Boeing Company', domain: 'boeing.com' },
  { symbol: 'CAT', name: 'Caterpillar Inc', domain: 'caterpillar.com' },
  { symbol: 'GE', name: 'General Electric Company', domain: 'ge.com' },
  { symbol: 'SPGI', name: 'S&P Global Inc', domain: 'spglobal.com' },
  { symbol: 'INTU', name: 'Intuit Inc', domain: 'intuit.com' },
  { symbol: 'DE', name: 'Deere & Company', domain: 'deere.com' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc', domain: 'bookingholdings.com' },
  { symbol: 'TJX', name: 'The TJX Companies Inc', domain: 'tjx.com' },
  { symbol: 'AXP', name: 'American Express Company', domain: 'americanexpress.com' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc', domain: 'gilead.com' },
  { symbol: 'MDT', name: 'Medtronic plc', domain: 'medtronic.com' },
  { symbol: 'BLK', name: 'BlackRock Inc', domain: 'blackrock.com' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', domain: 'starbucks.com' },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc', domain: 'adp.com' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies Inc', domain: 'marshmclennan.com' },
  { symbol: 'MDLZ', name: 'Mondelez International Inc', domain: 'mondelezinternational.com' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc', domain: 'intuitive.com' },
  { symbol: 'CVS', name: 'CVS Health Corporation', domain: 'cvshealth.com' },
  { symbol: 'NOW', name: 'ServiceNow Inc', domain: 'servicenow.com' },
  { symbol: 'CI', name: 'The Cigna Group', domain: 'cigna.com' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc', domain: 'vrtx.com' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc', domain: 'regeneron.com' },
  { symbol: 'ZTS', name: 'Zoetis Inc', domain: 'zoetis.com' },
  { symbol: 'PLD', name: 'Prologis Inc', domain: 'prologis.com' },
  { symbol: 'AMT', name: 'American Tower Corporation', domain: 'americantower.com' },
  { symbol: 'GS', name: 'The Goldman Sachs Group Inc', domain: 'goldmansachs.com' },
  { symbol: 'SO', name: 'The Southern Company', domain: 'southerncompany.com' },
  { symbol: 'SCHW', name: 'The Charles Schwab Corporation', domain: 'schwab.com' },
  { symbol: 'C', name: 'Citigroup Inc', domain: 'citigroup.com' },
  { symbol: 'MO', name: 'Altria Group Inc', domain: 'altria.com' },
  { symbol: 'CB', name: 'Chubb Limited', domain: 'chubb.com' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Company', domain: 'bms.com' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation', domain: 'lockheedmartin.com' },
  { symbol: 'PFE', name: 'Pfizer Inc', domain: 'pfizer.com' },
  { symbol: 'RTX', name: 'RTX Corporation', domain: 'rtx.com' },
  { symbol: 'ETN', name: 'Eaton Corporation plc', domain: 'eaton.com' },
  { symbol: 'BDX', name: 'Becton Dickinson and Company', domain: 'bd.com' },
  { symbol: 'DUK', name: 'Duke Energy Corporation', domain: 'duke-energy.com' },
  { symbol: 'SYK', name: 'Stryker Corporation', domain: 'stryker.com' },
  { symbol: 'ADI', name: 'Analog Devices Inc', domain: 'analog.com' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc', domain: 't-mobile.com' },
  { symbol: 'PGR', name: 'The Progressive Corporation', domain: 'progressive.com' },
  { symbol: 'CME', name: 'CME Group Inc', domain: 'cmegroup.com' },
  { symbol: 'MS', name: 'Morgan Stanley', domain: 'morganstanley.com' },
  { symbol: 'CL', name: 'Colgate-Palmolive Company', domain: 'colgatepalmolive.com' },
  { symbol: 'FI', name: 'Fiserv Inc', domain: 'fiserv.com' },
  { symbol: 'USB', name: 'U.S. Bancorp', domain: 'usbank.com' },
  { symbol: 'AMAT', name: 'Applied Materials Inc', domain: 'appliedmaterials.com' },
  { symbol: 'EOG', name: 'EOG Resources Inc', domain: 'eogresources.com' },
  { symbol: 'NSC', name: 'Norfolk Southern Corporation', domain: 'norfolksouthern.com' },
  { symbol: 'SLB', name: 'Schlumberger Limited', domain: 'slb.com' },
  { symbol: 'LRCX', name: 'Lam Research Corporation', domain: 'lamresearch.com' },
  { symbol: 'ITW', name: 'Illinois Tool Works Inc', domain: 'itw.com' },
  { symbol: 'AON', name: 'Aon plc', domain: 'aon.com' },
  { symbol: 'APD', name: 'Air Products and Chemicals Inc', domain: 'airproducts.com' },
  { symbol: 'HCA', name: 'HCA Healthcare Inc', domain: 'hcahealthcare.com' },
  { symbol: 'BSX', name: 'Boston Scientific Corporation', domain: 'bostonscientific.com' },
  { symbol: 'MMM', name: '3M Company', domain: '3m.com' },
  { symbol: 'ECL', name: 'Ecolab Inc', domain: 'ecolab.com' },
  { symbol: 'SHW', name: 'The Sherwin-Williams Company', domain: 'sherwin-williams.com' },
  { symbol: 'ICE', name: 'Intercontinental Exchange Inc', domain: 'theice.com' },
  { symbol: 'MPC', name: 'Marathon Petroleum Corporation', domain: 'marathonpetroleum.com' },
  { symbol: 'WM', name: 'Waste Management Inc', domain: 'wm.com' },
  { symbol: 'PNC', name: 'The PNC Financial Services Group', domain: 'pnc.com' },
  { symbol: 'COP', name: 'ConocoPhillips', domain: 'conocophillips.com' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc', domain: 'paypal.com' },
  { symbol: 'MCO', name: "Moody's Corporation", domain: 'moodys.com' },
  { symbol: 'CSX', name: 'CSX Corporation', domain: 'csx.com' },
  { symbol: 'GD', name: 'General Dynamics Corporation', domain: 'gd.com' },
  { symbol: 'PSX', name: 'Phillips 66', domain: 'phillips66.com' },
  { symbol: 'FCX', name: 'Freeport-McMoRan Inc', domain: 'fcx.com' },
  { symbol: 'EMR', name: 'Emerson Electric Co', domain: 'emerson.com' },
  { symbol: 'CCI', name: 'Crown Castle Inc', domain: 'crowncastle.com' },
  { symbol: 'TGT', name: 'Target Corporation', domain: 'target.com' },
  { symbol: 'EQIX', name: 'Equinix Inc', domain: 'equinix.com' },
  { symbol: 'ROP', name: 'Roper Technologies Inc', domain: 'ropertech.com' },
  { symbol: 'APH', name: 'Amphenol Corporation', domain: 'amphenol.com' },
  { symbol: 'MCK', name: 'McKesson Corporation', domain: 'mckesson.com' },
  { symbol: 'NOC', name: 'Northrop Grumman Corporation', domain: 'northropgrumman.com' },
  { symbol: 'WELL', name: 'Welltower Inc', domain: 'welltower.com' },
  { symbol: 'HUM', name: 'Humana Inc', domain: 'humana.com' },
  { symbol: 'AFL', name: 'Aflac Incorporated', domain: 'aflac.com' },
  { symbol: 'VLO', name: 'Valero Energy Corporation', domain: 'valero.com' },
  { symbol: 'AIG', name: 'American International Group', domain: 'aig.com' },
  { symbol: 'TT', name: 'Trane Technologies plc', domain: 'tranetechnologies.com' },
  { symbol: 'KMB', name: 'Kimberly-Clark Corporation', domain: 'kimberly-clark.com' },
  { symbol: 'MSCI', name: 'MSCI Inc', domain: 'msci.com' },
  { symbol: 'ALL', name: 'The Allstate Corporation', domain: 'allstate.com' },
  { symbol: 'TRV', name: 'The Travelers Companies Inc', domain: 'travelers.com' },
  { symbol: 'KLAC', name: 'KLA Corporation', domain: 'kla.com' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill Inc', domain: 'chipotle.com' },
  { symbol: 'SNPS', name: 'Synopsys Inc', domain: 'synopsys.com' },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc', domain: 'cadence.com' },
  { symbol: 'PAYX', name: 'Paychex Inc', domain: 'paychex.com' },
  { symbol: 'AEP', name: 'American Electric Power Company', domain: 'aep.com' },
  { symbol: 'O', name: 'Realty Income Corporation', domain: 'realtyincome.com' },
  { symbol: 'EW', name: 'Edwards Lifesciences Corporation', domain: 'edwards.com' },
  { symbol: 'CARR', name: 'Carrier Global Corporation', domain: 'carrier.com' },
  { symbol: 'SRE', name: 'Sempra', domain: 'sempra.com' },
  { symbol: 'TDG', name: 'TransDigm Group Inc', domain: 'transdigm.com' },
  { symbol: 'AZO', name: 'AutoZone Inc', domain: 'autozone.com' },
  { symbol: 'NXPI', name: 'NXP Semiconductors N.V.', domain: 'nxp.com' },
  { symbol: 'ROST', name: 'Ross Stores Inc', domain: 'rossstores.com' },
  { symbol: 'MCHP', name: 'Microchip Technology Inc', domain: 'microchip.com' },
  { symbol: 'PSA', name: 'Public Storage', domain: 'publicstorage.com' },
  { symbol: 'ORLY', name: "O'Reilly Automotive Inc", domain: 'oreillyauto.com' },
  { symbol: 'KMI', name: 'Kinder Morgan Inc', domain: 'kindermorgan.com' },
  { symbol: 'PCAR', name: 'PACCAR Inc', domain: 'paccar.com' },
  { symbol: 'MAR', name: 'Marriott International Inc', domain: 'marriott.com' },
  { symbol: 'ADSK', name: 'Autodesk Inc', domain: 'autodesk.com' },
  { symbol: 'SPG', name: 'Simon Property Group Inc', domain: 'simon.com' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher & Co', domain: 'ajg.com' },
  { symbol: 'BK', name: 'The Bank of New York Mellon Corp', domain: 'bnymellon.com' },
  { symbol: 'NEM', name: 'Newmont Corporation', domain: 'newmont.com' },
  { symbol: 'MNST', name: 'Monster Beverage Corporation', domain: 'monsterbevcorp.com' },
  { symbol: 'OXY', name: 'Occidental Petroleum Corporation', domain: 'oxy.com' },
  { symbol: 'EXC', name: 'Exelon Corporation', domain: 'exeloncorp.com' },
  { symbol: 'GM', name: 'General Motors Company', domain: 'gm.com' },
  { symbol: 'DD', name: 'DuPont de Nemours Inc', domain: 'dupont.com' },
  { symbol: 'CTVA', name: 'Corteva Inc', domain: 'corteva.com' },
  { symbol: 'TEL', name: 'TE Connectivity Ltd', domain: 'te.com' },
  { symbol: 'DHI', name: 'D.R. Horton Inc', domain: 'drhorton.com' },
  { symbol: 'D', name: 'Dominion Energy Inc', domain: 'dominionenergy.com' },
  { symbol: 'JCI', name: 'Johnson Controls International', domain: 'johnsoncontrols.com' },
  { symbol: 'LEN', name: 'Lennar Corporation', domain: 'lennar.com' },
  { symbol: 'GWW', name: 'W.W. Grainger Inc', domain: 'grainger.com' },
  { symbol: 'STZ', name: 'Constellation Brands Inc', domain: 'cbrands.com' },
  { symbol: 'CTAS', name: 'Cintas Corporation', domain: 'cintas.com' },
  { symbol: 'YUM', name: 'Yum! Brands Inc', domain: 'yum.com' },
  { symbol: 'HLT', name: 'Hilton Worldwide Holdings Inc', domain: 'hilton.com' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc', domain: 'digitalrealty.com' },
  { symbol: 'WMB', name: 'The Williams Companies Inc', domain: 'williams.com' },
  { symbol: 'FTNT', name: 'Fortinet Inc', domain: 'fortinet.com' },
  { symbol: 'RSG', name: 'Republic Services Inc', domain: 'republicservices.com' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc', domain: 'idexx.com' },
  { symbol: 'ON', name: 'ON Semiconductor Corporation', domain: 'onsemi.com' },
  { symbol: 'CPRT', name: 'Copart Inc', domain: 'copart.com' },
  { symbol: 'PCG', name: 'PG&E Corporation', domain: 'pgecorp.com' },
  { symbol: 'EL', name: 'The Estée Lauder Companies Inc', domain: 'esteelauder.com' },
  { symbol: 'DOW', name: 'Dow Inc', domain: 'dow.com' },
  { symbol: 'XEL', name: 'Xcel Energy Inc', domain: 'xcelenergy.com' },
  { symbol: 'A', name: 'Agilent Technologies Inc', domain: 'agilent.com' },
  { symbol: 'FAST', name: 'Fastenal Company', domain: 'fastenal.com' },
  { symbol: 'CMI', name: 'Cummins Inc', domain: 'cummins.com' },
  { symbol: 'ED', name: 'Consolidated Edison Inc', domain: 'conedison.com' },
  { symbol: 'AVB', name: 'AvalonBay Communities Inc', domain: 'avalonbay.com' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc', domain: 'dollartree.com' },
  { symbol: 'DXCM', name: 'DexCom Inc', domain: 'dexcom.com' },
  { symbol: 'HPQ', name: 'HP Inc', domain: 'hp.com' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', domain: 'hpe.com' },
  { symbol: 'ANSS', name: 'ANSYS Inc', domain: 'ansys.com' },
  { symbol: 'IT', name: 'Gartner Inc', domain: 'gartner.com' },
  { symbol: 'CHTR', name: 'Charter Communications Inc', domain: 'charter.com' },
  { symbol: 'EXR', name: 'Extra Space Storage Inc', domain: 'extraspace.com' },
  { symbol: 'F', name: 'Ford Motor Company', domain: 'ford.com' },
  { symbol: 'CBRE', name: 'CBRE Group Inc', domain: 'cbre.com' },
  { symbol: 'BKR', name: 'Baker Hughes Company', domain: 'bakerhughes.com' },
  { symbol: 'DG', name: 'Dollar General Corporation', domain: 'dollargeneral.com' },
  { symbol: 'ROK', name: 'Rockwell Automation Inc', domain: 'rockwellautomation.com' },
  { symbol: 'VICI', name: 'VICI Properties Inc', domain: 'viciproperties.com' },
  { symbol: 'DAL', name: 'Delta Air Lines Inc', domain: 'delta.com' },
  { symbol: 'KEYS', name: 'Keysight Technologies Inc', domain: 'keysight.com' },
  { symbol: 'FANG', name: 'Diamondback Energy Inc', domain: 'diamondbackenergy.com' },
  { symbol: 'IQV', name: 'IQVIA Holdings Inc', domain: 'iqvia.com' },
  { symbol: 'WBD', name: 'Warner Bros Discovery Inc', domain: 'wbd.com' },
  { symbol: 'VRSK', name: 'Verisk Analytics Inc', domain: 'verisk.com' },
  { symbol: 'GEHC', name: 'GE HealthCare Technologies Inc', domain: 'gehealthcare.com' },
  { symbol: 'EFX', name: 'Equifax Inc', domain: 'equifax.com' },
  { symbol: 'KVUE', name: 'Kenvue Inc', domain: 'kenvue.com' },
  { symbol: 'URI', name: 'United Rentals Inc', domain: 'unitedrentals.com' },
  { symbol: 'MTD', name: 'Mettler-Toledo International Inc', domain: 'mt.com' },
  { symbol: 'GLW', name: 'Corning Incorporated', domain: 'corning.com' },
  { symbol: 'WEC', name: 'WEC Energy Group Inc', domain: 'wecenergygroup.com' },
  { symbol: 'IR', name: 'Ingersoll Rand Inc', domain: 'irco.com' },
  { symbol: 'ACGL', name: 'Arch Capital Group Ltd', domain: 'archgroup.com' },
  { symbol: 'DHR', name: 'Danaher Corporation', domain: 'danaher.com' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems Inc', domain: 'monolithicpower.com' },
  { symbol: 'PWR', name: 'Quanta Services Inc', domain: 'quantaservices.com' },
  { symbol: 'EBAY', name: 'eBay Inc', domain: 'ebay.com' },
  { symbol: 'GIS', name: 'General Mills Inc', domain: 'generalmills.com' },
  { symbol: 'RMD', name: 'ResMed Inc', domain: 'resmed.com' },
  { symbol: 'ES', name: 'Eversource Energy', domain: 'eversource.com' },
  { symbol: 'VMC', name: 'Vulcan Materials Company', domain: 'vulcanmaterials.com' },
  { symbol: 'IFF', name: 'International Flavors & Fragrances', domain: 'iff.com' },
  { symbol: 'PPG', name: 'PPG Industries Inc', domain: 'ppg.com' },
  { symbol: 'STT', name: 'State Street Corporation', domain: 'statestreet.com' },
  { symbol: 'TSN', name: 'Tyson Foods Inc', domain: 'tysonfoods.com' },
  { symbol: 'VTR', name: 'Ventas Inc', domain: 'ventasreit.com' },
  { symbol: 'CDW', name: 'CDW Corporation', domain: 'cdw.com' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', domain: '53.com' },
  { symbol: 'TTWO', name: 'Take-Two Interactive Software', domain: 'take2games.com' },
  { symbol: 'MTB', name: 'M&T Bank Corporation', domain: 'mtb.com' },
  { symbol: 'INVH', name: 'Invitation Homes Inc', domain: 'invitationhomes.com' },
  { symbol: 'RCL', name: 'Royal Caribbean Cruises Ltd', domain: 'rclcorporate.com' },
  { symbol: 'UAL', name: 'United Airlines Holdings Inc', domain: 'united.com' },
  { symbol: 'FTV', name: 'Fortive Corporation', domain: 'fortive.com' },
  { symbol: 'AVY', name: 'Avery Dennison Corporation', domain: 'averydennison.com' },
  { symbol: 'K', name: 'Kellogg Company', domain: 'kelloggs.com' },
  { symbol: 'HBAN', name: 'Huntington Bancshares Inc', domain: 'huntington.com' },
  { symbol: 'FDS', name: 'FactSet Research Systems Inc', domain: 'factset.com' },
  { symbol: 'TYL', name: 'Tyler Technologies Inc', domain: 'tylertech.com' },
  { symbol: 'RF', name: 'Regions Financial Corporation', domain: 'regions.com' },
  { symbol: 'ARE', name: 'Alexandria Real Estate Equities', domain: 'are.com' },
  { symbol: 'BAX', name: 'Baxter International Inc', domain: 'baxter.com' },
  { symbol: 'SYF', name: 'Synchrony Financial', domain: 'synchrony.com' },
  { symbol: 'COF', name: 'Capital One Financial Corp', domain: 'capitalone.com' },
  { symbol: 'TDY', name: 'Teledyne Technologies Inc', domain: 'teledyne.com' },
  { symbol: 'TSCO', name: 'Tractor Supply Company', domain: 'tractorsupply.com' },
  { symbol: 'ALGN', name: 'Align Technology Inc', domain: 'aligntech.com' },
  { symbol: 'TROW', name: 'T. Rowe Price Group Inc', domain: 'troweprice.com' },
  { symbol: 'NTRS', name: 'Northern Trust Corporation', domain: 'northerntrust.com' },
  { symbol: 'CNP', name: 'CenterPoint Energy Inc', domain: 'centerpointenergy.com' },
  { symbol: 'CFG', name: 'Citizens Financial Group Inc', domain: 'citizensbank.com' },
  { symbol: 'STE', name: 'STERIS plc', domain: 'steris.com' },
  { symbol: 'HSY', name: 'The Hershey Company', domain: 'thehersheycompany.com' },
  { symbol: 'ZBRA', name: 'Zebra Technologies Corporation', domain: 'zebra.com' },
  { symbol: 'BBY', name: 'Best Buy Co Inc', domain: 'bestbuy.com' },
  { symbol: 'SWK', name: 'Stanley Black & Decker Inc', domain: 'stanleyblackanddecker.com' },
  { symbol: 'ULTA', name: 'Ulta Beauty Inc', domain: 'ulta.com' },
  { symbol: 'GPN', name: 'Global Payments Inc', domain: 'globalpayments.com' },
  { symbol: 'LH', name: 'Labcorp Holdings Inc', domain: 'labcorp.com' },
  { symbol: 'TER', name: 'Teradyne Inc', domain: 'teradyne.com' },
  { symbol: 'WAT', name: 'Waters Corporation', domain: 'waters.com' },
  { symbol: 'IRM', name: 'Iron Mountain Inc', domain: 'ironmountain.com' },
  { symbol: 'NTAP', name: 'NetApp Inc', domain: 'netapp.com' },
  { symbol: 'MOH', name: 'Molina Healthcare Inc', domain: 'molinahealthcare.com' },
  { symbol: 'BALL', name: 'Ball Corporation', domain: 'ball.com' },
  { symbol: 'WTW', name: 'Willis Towers Watson Public Ltd', domain: 'wtwco.com' },
  { symbol: 'EXPE', name: 'Expedia Group Inc', domain: 'expediagroup.com' },
  { symbol: 'CAH', name: 'Cardinal Health Inc', domain: 'cardinalhealth.com' },
  { symbol: 'PODD', name: 'Insulet Corporation', domain: 'insulet.com' },
  { symbol: 'LYB', name: 'LyondellBasell Industries N.V.', domain: 'lyondellbasell.com' },
  { symbol: 'TRGP', name: 'Targa Resources Corp', domain: 'targaresources.com' },
  { symbol: 'AWK', name: 'American Water Works Company Inc', domain: 'amwater.com' },
  { symbol: 'DFS', name: 'Discover Financial Services', domain: 'discover.com' },
  { symbol: 'APTV', name: 'Aptiv PLC', domain: 'aptiv.com' },
  { symbol: 'CE', name: 'Celanese Corporation', domain: 'celanese.com' },
  { symbol: 'ETR', name: 'Entergy Corporation', domain: 'entergy.com' },
  { symbol: 'CCL', name: 'Carnival Corporation', domain: 'carnivalcorp.com' },
  { symbol: 'EIX', name: 'Edison International', domain: 'edison.com' },
  { symbol: 'WY', name: 'Weyerhaeuser Company', domain: 'weyerhaeuser.com' },
  { symbol: 'EPAM', name: 'EPAM Systems Inc', domain: 'epam.com' },
  { symbol: 'DOV', name: 'Dover Corporation', domain: 'dovercorporation.com' },
  { symbol: 'PFG', name: 'Principal Financial Group Inc', domain: 'principal.com' },
  { symbol: 'CTLT', name: 'Catalent Inc', domain: 'catalent.com' },
  { symbol: 'LDOS', name: 'Leidos Holdings Inc', domain: 'leidos.com' },
  { symbol: 'FE', name: 'FirstEnergy Corp', domain: 'firstenergycorp.com' },
  { symbol: 'LVS', name: 'Las Vegas Sands Corp', domain: 'sands.com' },
  { symbol: 'ZBH', name: 'Zimmer Biomet Holdings Inc', domain: 'zimmerbiomet.com' },
  { symbol: 'PKG', name: 'Packaging Corporation of America', domain: 'packagingcorp.com' },
  { symbol: 'BLDR', name: 'Builders FirstSource Inc', domain: 'bldr.com' },
  { symbol: 'BR', name: 'Broadridge Financial Solutions', domain: 'broadridge.com' },
  { symbol: 'MKC', name: 'McCormick & Company Inc', domain: 'mccormickcorporation.com' },
  { symbol: 'HIG', name: 'The Hartford Financial Services', domain: 'thehartford.com' },
  { symbol: 'KEY', name: 'KeyCorp', domain: 'key.com' },
  { symbol: 'SYY', name: 'Sysco Corporation', domain: 'sysco.com' },
  { symbol: 'DRI', name: 'Darden Restaurants Inc', domain: 'darden.com' },
  { symbol: 'WAB', name: 'Westinghouse Air Brake Technologies', domain: 'wabteccorp.com' },
  { symbol: 'J', name: 'Jacobs Solutions Inc', domain: 'jacobs.com' },
  { symbol: 'POOL', name: 'Pool Corporation', domain: 'poolcorp.com' },
  { symbol: 'GRMN', name: 'Garmin Ltd', domain: 'garmin.com' },
  { symbol: 'JBHT', name: 'J.B. Hunt Transport Services Inc', domain: 'jbhunt.com' },
  { symbol: 'CTRA', name: 'Coterra Energy Inc', domain: 'coterraenergy.com' },
  { symbol: 'L', name: 'Loews Corporation', domain: 'loews.com' },
  { symbol: 'HST', name: 'Host Hotels & Resorts Inc', domain: 'hosthotels.com' },
  { symbol: 'JKHY', name: 'Jack Henry & Associates Inc', domain: 'jackhenry.com' },
  { symbol: 'TPR', name: 'Tapestry Inc', domain: 'tapestry.com' },
  { symbol: 'BXP', name: 'Boston Properties Inc', domain: 'bostonproperties.com' },
  { symbol: 'AMCR', name: 'Amcor plc', domain: 'amcor.com' },
  { symbol: 'INCY', name: 'Incyte Corporation', domain: 'incyte.com' },
  { symbol: 'NDSN', name: 'Nordson Corporation', domain: 'nordson.com' },
  { symbol: 'LUV', name: 'Southwest Airlines Co', domain: 'southwest.com' },
  { symbol: 'VTRS', name: 'Viatris Inc', domain: 'viatris.com' },
  { symbol: 'IP', name: 'International Paper Company', domain: 'internationalpaper.com' },
  { symbol: 'RL', name: 'Ralph Lauren Corporation', domain: 'ralphlauren.com' },
  { symbol: 'HWM', name: 'Howmet Aerospace Inc', domain: 'howmet.com' },
  { symbol: 'SWKS', name: 'Skyworks Solutions Inc', domain: 'skyworksinc.com' },
  { symbol: 'PNR', name: 'Pentair plc', domain: 'pentair.com' },
  { symbol: 'AES', name: 'The AES Corporation', domain: 'aes.com' },
  { symbol: 'CPT', name: 'Camden Property Trust', domain: 'camdenliving.com' },
  { symbol: 'TXT', name: 'Textron Inc', domain: 'textron.com' },
  { symbol: 'CRL', name: 'Charles River Laboratories', domain: 'criver.com' },
  { symbol: 'ENPH', name: 'Enphase Energy Inc', domain: 'enphase.com' },
  { symbol: 'MAS', name: 'Masco Corporation', domain: 'masco.com' },
  { symbol: 'NVR', name: 'NVR Inc', domain: 'nvrinc.com' },
  { symbol: 'AKAM', name: 'Akamai Technologies Inc', domain: 'akamai.com' },
  { symbol: 'ATO', name: 'Atmos Energy Corporation', domain: 'atmosenergy.com' },
  { symbol: 'EXPD', name: 'Expeditors International', domain: 'expeditors.com' },
  { symbol: 'NI', name: 'NiSource Inc', domain: 'nisource.com' },
  { symbol: 'NRG', name: 'NRG Energy Inc', domain: 'nrg.com' },
  { symbol: 'CHRW', name: 'C.H. Robinson Worldwide Inc', domain: 'chrobinson.com' },
  { symbol: 'LKQ', name: 'LKQ Corporation', domain: 'lkqcorp.com' },
  { symbol: 'PAYC', name: 'Paycom Software Inc', domain: 'paycom.com' },
  { symbol: 'BEN', name: 'Franklin Resources Inc', domain: 'franklintempleton.com' },
  { symbol: 'TECH', name: 'Bio-Techne Corporation', domain: 'bio-techne.com' },
  { symbol: 'ALB', name: 'Albemarle Corporation', domain: 'albemarle.com' },
  { symbol: 'AAL', name: 'American Airlines Group Inc', domain: 'aa.com' },
  { symbol: 'KR', name: 'The Kroger Co', domain: 'kroger.com' },
  { symbol: 'MGM', name: 'MGM Resorts International', domain: 'mgmresorts.com' },
  { symbol: 'WYNN', name: 'Wynn Resorts Limited', domain: 'wynnresorts.com' },
  { symbol: 'SNAP', name: 'Snap Inc', domain: 'snap.com' },
  { symbol: 'UBER', name: 'Uber Technologies Inc', domain: 'uber.com' },
  { symbol: 'LYFT', name: 'Lyft Inc', domain: 'lyft.com' },
  { symbol: 'ABNB', name: 'Airbnb Inc', domain: 'airbnb.com' },
  { symbol: 'COIN', name: 'Coinbase Global Inc', domain: 'coinbase.com' },
  { symbol: 'RIVN', name: 'Rivian Automotive Inc', domain: 'rivian.com' },
  { symbol: 'LCID', name: 'Lucid Group Inc', domain: 'lucidmotors.com' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc', domain: 'palantir.com' },
  { symbol: 'SNOW', name: 'Snowflake Inc', domain: 'snowflake.com' },
  { symbol: 'ZM', name: 'Zoom Video Communications Inc', domain: 'zoom.us' },
  { symbol: 'DOCU', name: 'DocuSign Inc', domain: 'docusign.com' },
  { symbol: 'ROKU', name: 'Roku Inc', domain: 'roku.com' },
  { symbol: 'SQ', name: 'Block Inc', domain: 'block.xyz' },
  { symbol: 'SHOP', name: 'Shopify Inc', domain: 'shopify.com' },
  { symbol: 'SPOT', name: 'Spotify Technology SA', domain: 'spotify.com' },
  { symbol: 'TWLO', name: 'Twilio Inc', domain: 'twilio.com' },
  { symbol: 'OKTA', name: 'Okta Inc', domain: 'okta.com' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc', domain: 'crowdstrike.com' },
  { symbol: 'NET', name: 'Cloudflare Inc', domain: 'cloudflare.com' },
  { symbol: 'DDOG', name: 'Datadog Inc', domain: 'datadoghq.com' },
  { symbol: 'MDB', name: 'MongoDB Inc', domain: 'mongodb.com' },
  { symbol: 'TEAM', name: 'Atlassian Corporation', domain: 'atlassian.com' },
  { symbol: 'ZS', name: 'Zscaler Inc', domain: 'zscaler.com' },
  { symbol: 'PINS', name: 'Pinterest Inc', domain: 'pinterest.com' },
  { symbol: 'RBLX', name: 'Roblox Corporation', domain: 'roblox.com' },
  { symbol: 'U', name: 'Unity Software Inc', domain: 'unity.com' },
  { symbol: 'DASH', name: 'DoorDash Inc', domain: 'doordash.com' },
  { symbol: 'ABNB', name: 'Airbnb Inc', domain: 'airbnb.com' },
  { symbol: 'PTON', name: 'Peloton Interactive Inc', domain: 'onepeloton.com' },
  { symbol: 'MRNA', name: 'Moderna Inc', domain: 'modernatx.com' },
  { symbol: 'BNTX', name: 'BioNTech SE', domain: 'biontech.com' },
  { symbol: 'HOOD', name: 'Robinhood Markets Inc', domain: 'robinhood.com' },
  { symbol: 'SOFI', name: 'SoFi Technologies Inc', domain: 'sofi.com' },
  { symbol: 'AFRM', name: 'Affirm Holdings Inc', domain: 'affirm.com' },
  { symbol: 'RDFN', name: 'Redfin Corporation', domain: 'redfin.com' },
  { symbol: 'CVNA', name: 'Carvana Co', domain: 'carvana.com' },
  { symbol: 'W', name: 'Wayfair Inc', domain: 'wayfair.com' },
  { symbol: 'ETSY', name: 'Etsy Inc', domain: 'etsy.com' },
  { symbol: 'ZG', name: 'Zillow Group Inc', domain: 'zillow.com' },
  { symbol: 'CHWY', name: 'Chewy Inc', domain: 'chewy.com' },
  { symbol: 'BYND', name: 'Beyond Meat Inc', domain: 'beyondmeat.com' },
  { symbol: 'TWTR', name: 'Twitter Inc', domain: 'twitter.com' },
  { symbol: 'SLV', name: 'iShares Silver Trust', domain: 'ishares.com' },
  { symbol: 'GLD', name: 'SPDR Gold Shares', domain: 'spdrgoldshares.com' },
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust', domain: 'ssga.com' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', domain: 'invesco.com' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF', domain: 'ishares.com' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF', domain: 'vanguard.com' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF', domain: 'vanguard.com' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', domain: 'ark-invest.com' },
  { symbol: 'TSMC', name: 'Taiwan Semiconductor Manufacturing', domain: 'tsmc.com' },
  { symbol: 'ASML', name: 'ASML Holding N.V.', domain: 'asml.com' },
  { symbol: 'NIO', name: 'NIO Inc', domain: 'nio.com' },
  { symbol: 'XPEV', name: 'XPeng Inc', domain: 'xiaopeng.com' },
  { symbol: 'LI', name: 'Li Auto Inc', domain: 'lixiang.com' },
  { symbol: 'BABA', name: 'Alibaba Group Holding Ltd', domain: 'alibaba.com' },
  { symbol: 'BIDU', name: 'Baidu Inc', domain: 'baidu.com' },
  { symbol: 'JD', name: 'JD.com Inc', domain: 'jd.com' },
  { symbol: 'PDD', name: 'PDD Holdings Inc', domain: 'pinduoduo.com' },
  { symbol: 'NTES', name: 'NetEase Inc', domain: 'netease.com' },
  { symbol: 'TME', name: 'Tencent Music Entertainment', domain: 'tencentmusic.com' },
  { symbol: 'SE', name: 'Sea Limited', domain: 'sea.com' },
  { symbol: 'GRAB', name: 'Grab Holdings Limited', domain: 'grab.com' },
  { symbol: 'MELI', name: 'MercadoLibre Inc', domain: 'mercadolibre.com' },
  { symbol: 'NU', name: 'Nu Holdings Ltd', domain: 'nu.com.br' },
  { symbol: 'SAP', name: 'SAP SE', domain: 'sap.com' },
  { symbol: 'SONY', name: 'Sony Group Corporation', domain: 'sony.com' },
  { symbol: 'TM', name: 'Toyota Motor Corporation', domain: 'toyota.com' },
  { symbol: 'HMC', name: 'Honda Motor Co Ltd', domain: 'honda.com' },
  { symbol: 'RACE', name: 'Ferrari N.V.', domain: 'ferrari.com' },
  { symbol: 'STLA', name: 'Stellantis N.V.', domain: 'stellantis.com' },
  { symbol: 'DELL', name: 'Dell Technologies Inc', domain: 'dell.com' },
  { symbol: 'SMCI', name: 'Super Micro Computer Inc', domain: 'supermicro.com' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc', domain: 'paloaltonetworks.com' },
  { symbol: 'WDAY', name: 'Workday Inc', domain: 'workday.com' },
  { symbol: 'VEEV', name: 'Veeva Systems Inc', domain: 'veeva.com' },
  { symbol: 'SPLK', name: 'Splunk Inc', domain: 'splunk.com' },
  { symbol: 'CZR', name: 'Caesars Entertainment Inc', domain: 'caesars.com' },
  { symbol: 'PENN', name: 'Penn Entertainment Inc', domain: 'pennentertainment.com' },
  { symbol: 'DKNG', name: 'DraftKings Inc', domain: 'draftkings.com' },
  { symbol: 'BKKT', name: 'Bakkt Holdings Inc', domain: 'bakkt.com' },
  { symbol: 'PATH', name: 'UiPath Inc', domain: 'uipath.com' },
  { symbol: 'BILL', name: 'Bill.com Holdings Inc', domain: 'bill.com' },
  { symbol: 'SYM', name: 'Symbotic Inc', domain: 'symbotic.com' },
  { symbol: 'IONQ', name: 'IonQ Inc', domain: 'ionq.com' },
  { symbol: 'QCOM', name: 'Qualcomm Inc', domain: 'qualcomm.com' },
  { symbol: 'ARM', name: 'Arm Holdings plc', domain: 'arm.com' },
  { symbol: 'MRVL', name: 'Marvell Technology Inc', domain: 'marvell.com' },
  { symbol: 'MU', name: 'Micron Technology Inc', domain: 'micron.com' },
  { symbol: 'WDC', name: 'Western Digital Corporation', domain: 'westerndigital.com' },
  { symbol: 'STX', name: 'Seagate Technology Holdings plc', domain: 'seagate.com' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc', domain: 'lululemon.com' },
  { symbol: 'DECK', name: 'Deckers Outdoor Corporation', domain: 'deckers.com' },
  { symbol: 'CROX', name: 'Crocs Inc', domain: 'crocs.com' },
  { symbol: 'VFC', name: 'V.F. Corporation', domain: 'vfc.com' },
  { symbol: 'UAA', name: 'Under Armour Inc', domain: 'underarmour.com' },
  { symbol: 'CPNG', name: 'Coupang Inc', domain: 'coupang.com' },
  { symbol: 'NTNX', name: 'Nutanix Inc', domain: 'nutanix.com' },
  { symbol: 'DBX', name: 'Dropbox Inc', domain: 'dropbox.com' },
  { symbol: 'BOX', name: 'Box Inc', domain: 'box.com' },
  { symbol: 'FIVN', name: 'Five9 Inc', domain: 'five9.com' },
  { symbol: 'GTLB', name: 'GitLab Inc', domain: 'gitlab.com' },
  { symbol: 'CFLT', name: 'Confluent Inc', domain: 'confluent.io' },
  { symbol: 'ESTC', name: 'Elastic N.V.', domain: 'elastic.co' },
  { symbol: 'HUBS', name: 'HubSpot Inc', domain: 'hubspot.com' },
  { symbol: 'ZI', name: 'ZoomInfo Technologies Inc', domain: 'zoominfo.com' },
  { symbol: 'SMAR', name: 'Smartsheet Inc', domain: 'smartsheet.com' },
  { symbol: 'PTC', name: 'PTC Inc', domain: 'ptc.com' },
  { symbol: 'ASAN', name: 'Asana Inc', domain: 'asana.com' },
  { symbol: 'MNDY', name: 'Monday.com Ltd', domain: 'monday.com' },
  { symbol: 'DUOL', name: 'Duolingo Inc', domain: 'duolingo.com' },
  { symbol: 'BMBL', name: 'Bumble Inc', domain: 'bumble.com' },
  { symbol: 'MTCH', name: 'Match Group Inc', domain: 'mtch.com' },
  { symbol: 'RBLX', name: 'Roblox Corporation', domain: 'roblox.com' },
  { symbol: 'EA', name: 'Electronic Arts Inc', domain: 'ea.com' },
  { symbol: 'ATVI', name: 'Activision Blizzard Inc', domain: 'activisionblizzard.com' },
  { symbol: 'TTWO', name: 'Take-Two Interactive Software', domain: 'take2games.com' },
  { symbol: 'ZNGA', name: 'Zynga Inc', domain: 'zynga.com' },
  { symbol: 'DKNG', name: 'DraftKings Inc', domain: 'draftkings.com' },
  { symbol: 'FLUT', name: 'Flutter Entertainment plc', domain: 'flutter.com' },
  { symbol: 'MSGS', name: 'Madison Square Garden Sports Corp', domain: 'msg.com' },
  { symbol: 'FUBO', name: 'fuboTV Inc', domain: 'fubo.tv' },
  { symbol: 'PARA', name: 'Paramount Global', domain: 'paramount.com' },
  { symbol: 'FOXA', name: 'Fox Corporation', domain: 'foxcorporation.com' },
  { symbol: 'NWSA', name: 'News Corp', domain: 'newscorp.com' },
  { symbol: 'NYT', name: 'The New York Times Company', domain: 'nytimes.com' },
  { symbol: 'LYV', name: 'Live Nation Entertainment Inc', domain: 'livenationentertainment.com' },
  { symbol: 'MSGS', name: 'Madison Square Garden Sports Corp', domain: 'msg.com' },
  { symbol: 'WBD', name: 'Warner Bros Discovery Inc', domain: 'wbd.com' },
  { symbol: 'SPOT', name: 'Spotify Technology SA', domain: 'spotify.com' },
  { symbol: 'SIRI', name: 'Sirius XM Holdings Inc', domain: 'siriusxm.com' },
  { symbol: 'LITE', name: 'Lumentum Holdings Inc', domain: 'lumentum.com' },
  { symbol: 'COHR', name: 'Coherent Corp', domain: 'coherent.com' },
  { symbol: 'VIAV', name: 'Viavi Solutions Inc', domain: 'viavisolutions.com' },
  { symbol: 'JNPR', name: 'Juniper Networks Inc', domain: 'juniper.net' },
  { symbol: 'FFIV', name: 'F5 Inc', domain: 'f5.com' },
  { symbol: 'AKAM', name: 'Akamai Technologies Inc', domain: 'akamai.com' },
  { symbol: 'CTXS', name: 'Citrix Systems Inc', domain: 'citrix.com' },
  { symbol: 'VMW', name: 'VMware Inc', domain: 'vmware.com' },
  { symbol: 'RNG', name: 'RingCentral Inc', domain: 'ringcentral.com' },
  { symbol: 'NICE', name: 'NICE Ltd', domain: 'nice.com' },
  { symbol: 'CYBR', name: 'CyberArk Software Ltd', domain: 'cyberark.com' },
  { symbol: 'TENB', name: 'Tenable Holdings Inc', domain: 'tenable.com' },
  { symbol: 'S', name: 'SentinelOne Inc', domain: 'sentinelone.com' },
  { symbol: 'CHKP', name: 'Check Point Software Technologies', domain: 'checkpoint.com' },
  { symbol: 'GEN', name: 'Gen Digital Inc', domain: 'gendigital.com' },
  { symbol: 'QLYS', name: 'Qualys Inc', domain: 'qualys.com' },
  { symbol: 'SAIL', name: 'SailPoint Technologies Holdings', domain: 'sailpoint.com' },
  { symbol: 'PFPT', name: 'Proofpoint Inc', domain: 'proofpoint.com' },
  { symbol: 'RPD', name: 'Rapid7 Inc', domain: 'rapid7.com' },
  { symbol: 'VRNS', name: 'Varonis Systems Inc', domain: 'varonis.com' },
  { symbol: 'PCTY', name: 'Paylocity Holding Corporation', domain: 'paylocity.com' },
  { symbol: 'PAYC', name: 'Paycom Software Inc', domain: 'paycom.com' },
  { symbol: 'PCOR', name: 'Procore Technologies Inc', domain: 'procore.com' },
  { symbol: 'BLKB', name: 'Blackbaud Inc', domain: 'blackbaud.com' },
  { symbol: 'COUP', name: 'Coupa Software Inc', domain: 'coupa.com' },
  { symbol: 'APPF', name: 'AppFolio Inc', domain: 'appfolio.com' },
  { symbol: 'APPN', name: 'Appian Corporation', domain: 'appian.com' },
  { symbol: 'PLAN', name: 'Anaplan Inc', domain: 'anaplan.com' },
  { symbol: 'ALTR', name: 'Altair Engineering Inc', domain: 'altair.com' },
  { symbol: 'GWRE', name: 'Guidewire Software Inc', domain: 'guidewire.com' },
  { symbol: 'RXT', name: 'Rackspace Technology Inc', domain: 'rackspace.com' },
  { symbol: 'FSLY', name: 'Fastly Inc', domain: 'fastly.com' },
  { symbol: 'EQIX', name: 'Equinix Inc', domain: 'equinix.com' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc', domain: 'digitalrealty.com' },
  { symbol: 'COR', name: 'Cencora Inc', domain: 'cencora.com' },
  { symbol: 'HSIC', name: 'Henry Schein Inc', domain: 'henryschein.com' },
  { symbol: 'PDCO', name: 'Patterson Companies Inc', domain: 'pattersondental.com' },
  { symbol: 'ABC', name: 'AmerisourceBergen Corporation', domain: 'amerisourcebergen.com' },
  { symbol: 'MCK', name: 'McKesson Corporation', domain: 'mckesson.com' },
  { symbol: 'CAH', name: 'Cardinal Health Inc', domain: 'cardinalhealth.com' },
  { symbol: 'HOLX', name: 'Hologic Inc', domain: 'hologic.com' },
  { symbol: 'DXCM', name: 'DexCom Inc', domain: 'dexcom.com' },
  { symbol: 'PODD', name: 'Insulet Corporation', domain: 'insulet.com' },
  { symbol: 'TNDM', name: 'Tandem Diabetes Care Inc', domain: 'tandemdiabetes.com' },
  { symbol: 'PEN', name: 'Penumbra Inc', domain: 'penumbrainc.com' },
  { symbol: 'NVST', name: 'Envista Holdings Corporation', domain: 'envistaco.com' },
  { symbol: 'XRAY', name: 'DENTSPLY SIRONA Inc', domain: 'dentsplysirona.com' },
  { symbol: 'NVCR', name: 'NovoCure Limited', domain: 'novocure.com' },
  { symbol: 'STAA', name: 'STAAR Surgical Company', domain: 'staar.com' },
  { symbol: 'GKOS', name: 'Glaukos Corporation', domain: 'glaukos.com' },
  { symbol: 'ICUI', name: 'ICU Medical Inc', domain: 'icumed.com' },
  { symbol: 'MMSI', name: 'Merit Medical Systems Inc', domain: 'merit.com' },
  { symbol: 'NARI', name: 'Inari Medical Inc', domain: 'inarimedical.com' },
  { symbol: 'IRTC', name: 'iRhythm Technologies Inc', domain: 'irhythmtech.com' },
  { symbol: 'AXNX', name: 'Axonics Inc', domain: 'axonicsmodulation.com' },
  { symbol: 'QDEL', name: 'QuidelOrtho Corporation', domain: 'quidel.com' },
  { symbol: 'TECH', name: 'Bio-Techne Corporation', domain: 'bio-techne.com' },
  { symbol: 'BMRN', name: 'BioMarin Pharmaceutical Inc', domain: 'biomarin.com' },
  { symbol: 'SRPT', name: 'Sarepta Therapeutics Inc', domain: 'sarepta.com' },
  { symbol: 'ALNY', name: 'Alnylam Pharmaceuticals Inc', domain: 'alnylam.com' },
  { symbol: 'IONS', name: 'Ionis Pharmaceuticals Inc', domain: 'ionispharma.com' },
  { symbol: 'UTHR', name: 'United Therapeutics Corporation', domain: 'unither.com' },
  { symbol: 'JAZZ', name: 'Jazz Pharmaceuticals plc', domain: 'jazzpharma.com' },
  { symbol: 'NBIX', name: 'Neurocrine Biosciences Inc', domain: 'neurocrine.com' },
  { symbol: 'EXEL', name: 'Exelixis Inc', domain: 'exelixis.com' },
  { symbol: 'HALO', name: 'Halozyme Therapeutics Inc', domain: 'halozyme.com' },
  { symbol: 'RGNX', name: 'REGENXBIO Inc', domain: 'regenxbio.com' },
  { symbol: 'RARE', name: 'Ultragenyx Pharmaceutical Inc', domain: 'ultragenyx.com' },
  { symbol: 'FOLD', name: 'Amicus Therapeutics Inc', domain: 'amicusrx.com' },
  { symbol: 'BGNE', name: 'BeiGene Ltd', domain: 'beigene.com' },
  { symbol: 'LEGN', name: 'Legend Biotech Corporation', domain: 'legendbiotech.com' },
  { symbol: 'ARVN', name: 'Arvinas Inc', domain: 'arvinas.com' },
  { symbol: 'CRSP', name: 'CRISPR Therapeutics AG', domain: 'crisprtx.com' },
  { symbol: 'EDIT', name: 'Editas Medicine Inc', domain: 'editasmedicine.com' },
  { symbol: 'NTLA', name: 'Intellia Therapeutics Inc', domain: 'intelliatx.com' },
  { symbol: 'BEAM', name: 'Beam Therapeutics Inc', domain: 'beamtx.com' },
  { symbol: 'BLUE', name: 'bluebird bio Inc', domain: 'bluebirdbio.com' },
  { symbol: 'SAGE', name: 'Sage Therapeutics Inc', domain: 'sagerx.com' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc', domain: 'vrtx.com' },
  { symbol: 'INCY', name: 'Incyte Corporation', domain: 'incyte.com' },
  { symbol: 'EXAS', name: 'Exact Sciences Corporation', domain: 'exactsciences.com' },
  { symbol: 'ILMN', name: 'Illumina Inc', domain: 'illumina.com' },
  { symbol: 'A', name: 'Agilent Technologies Inc', domain: 'agilent.com' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc', domain: 'thermofisher.com' },
  { symbol: 'DHR', name: 'Danaher Corporation', domain: 'danaher.com' },
  { symbol: 'WAT', name: 'Waters Corporation', domain: 'waters.com' },
  { symbol: 'PKI', name: 'PerkinElmer Inc', domain: 'perkinelmer.com' },
  { symbol: 'BIO', name: 'Bio-Rad Laboratories Inc', domain: 'bio-rad.com' },
  { symbol: 'QGEN', name: 'QIAGEN N.V.', domain: 'qiagen.com' },
  { symbol: 'IQV', name: 'IQVIA Holdings Inc', domain: 'iqvia.com' },
  { symbol: 'CRL', name: 'Charles River Laboratories', domain: 'criver.com' },
  { symbol: 'LH', name: 'Labcorp Holdings Inc', domain: 'labcorp.com' },
  { symbol: 'DGX', name: 'Quest Diagnostics Inc', domain: 'questdiagnostics.com' },
  { symbol: 'FSLR', name: 'First Solar Inc', domain: 'firstsolar.com' },
  { symbol: 'SEDG', name: 'SolarEdge Technologies Inc', domain: 'solaredge.com' },
  { symbol: 'RUN', name: 'Sunrun Inc', domain: 'sunrun.com' },
  { symbol: 'NEP', name: 'NextEra Energy Partners LP', domain: 'nexteraenergypartners.com' },
  { symbol: 'PLUG', name: 'Plug Power Inc', domain: 'plugpower.com' },
  { symbol: 'BE', name: 'Bloom Energy Corporation', domain: 'bloomenergy.com' },
  { symbol: 'FCEL', name: 'FuelCell Energy Inc', domain: 'fuelcellenergy.com' },
  { symbol: 'NOVA', name: 'Sunnova Energy International Inc', domain: 'sunnova.com' },
  { symbol: 'ARRY', name: 'Array Technologies Inc', domain: 'arraytechinc.com' },
  { symbol: 'CSIQ', name: 'Canadian Solar Inc', domain: 'canadiansolar.com' },
  { symbol: 'JKS', name: 'JinkoSolar Holding Co Ltd', domain: 'jinkosolar.com' },
  { symbol: 'DQ', name: 'Daqo New Energy Corp', domain: 'daqo.com' },
  { symbol: 'MAXN', name: 'Maxeon Solar Technologies Ltd', domain: 'maxeon.com' },
  { symbol: 'SPWR', name: 'SunPower Corporation', domain: 'sunpower.com' },
  { symbol: 'SHLS', name: 'Shoals Technologies Group Inc', domain: 'shoals.com' },
  { symbol: 'CHPT', name: 'ChargePoint Holdings Inc', domain: 'chargepoint.com' },
  { symbol: 'BLNK', name: 'Blink Charging Co', domain: 'blinkcharging.com' },
  { symbol: 'EVGO', name: 'EVgo Inc', domain: 'evgo.com' },
  { symbol: 'STEM', name: 'Stem Inc', domain: 'stem.com' },
  { symbol: 'FLNC', name: 'Fluence Energy Inc', domain: 'fluenceenergy.com' },
  { symbol: 'NOVA', name: 'Sunnova Energy International Inc', domain: 'sunnova.com' },
  { symbol: 'ORA', name: 'Ormat Technologies Inc', domain: 'ormat.com' },
  { symbol: 'CWEN', name: 'Clearway Energy Inc', domain: 'clearwayenergy.com' },
  { symbol: 'AY', name: 'Atlantica Sustainable Infrastructure', domain: 'atlantica.com' },
  { symbol: 'VSTS', name: 'Vestis Corporation', domain: 'vestis.com' },
  { symbol: 'JOBY', name: 'Joby Aviation Inc', domain: 'jobyaviation.com' },
  { symbol: 'ACHR', name: 'Archer Aviation Inc', domain: 'archer.com' },
  { symbol: 'LILM', name: 'Lilium N.V.', domain: 'lilium.com' },
  { symbol: 'EVTL', name: 'Vertical Aerospace Ltd', domain: 'vertical-aerospace.com' },
  { symbol: 'MP', name: 'MP Materials Corp', domain: 'mpmaterials.com' },
  { symbol: 'LAC', name: 'Lithium Americas Corp', domain: 'lithiumamericas.com' },
  { symbol: 'SQM', name: 'Sociedad Quimica y Minera de Chile', domain: 'sqm.com' },
  { symbol: 'LTHM', name: 'Livent Corporation', domain: 'livent.com' },
  { symbol: 'PLL', name: 'Piedmont Lithium Inc', domain: 'piedmontlithium.com' },
  { symbol: 'TECK', name: 'Teck Resources Limited', domain: 'teck.com' },
  { symbol: 'CLF', name: 'Cleveland-Cliffs Inc', domain: 'clevelandcliffs.com' },
  { symbol: 'STLD', name: 'Steel Dynamics Inc', domain: 'steeldynamics.com' },
  { symbol: 'NUE', name: 'Nucor Corporation', domain: 'nucor.com' },
  { symbol: 'X', name: 'United States Steel Corporation', domain: 'ussteel.com' },
  { symbol: 'MT', name: 'ArcelorMittal', domain: 'arcelormittal.com' },
  { symbol: 'RS', name: 'Reliance Steel & Aluminum Co', domain: 'rsac.com' },
  { symbol: 'CMC', name: 'Commercial Metals Company', domain: 'cmc.com' },
  { symbol: 'WOR', name: 'Worthington Industries Inc', domain: 'worthingtonindustries.com' },
  { symbol: 'ATI', name: 'ATI Inc', domain: 'atimetals.com' },
  { symbol: 'CENX', name: 'Century Aluminum Company', domain: 'centuryaluminum.com' },
  { symbol: 'AA', name: 'Alcoa Corporation', domain: 'alcoa.com' },
  { symbol: 'ACH', name: 'Aluminum Corporation of China', domain: 'chalco.com.cn' },
  { symbol: 'SCCO', name: 'Southern Copper Corporation', domain: 'southernperu.com' },
  { symbol: 'TRGP', name: 'Targa Resources Corp', domain: 'targaresources.com' },
  { symbol: 'OKE', name: 'ONEOK Inc', domain: 'oneok.com' },
  { symbol: 'AM', name: 'Antero Midstream Corporation', domain: 'anteromidstream.com' },
  { symbol: 'EPD', name: 'Enterprise Products Partners LP', domain: 'enterpriseproducts.com' },
  { symbol: 'PAA', name: 'Plains All American Pipeline LP', domain: 'plains.com' },
  { symbol: 'MMP', name: 'Magellan Midstream Partners LP', domain: 'magellanlp.com' },
  { symbol: 'MPLX', name: 'MPLX LP', domain: 'mplx.com' },
  { symbol: 'ET', name: 'Energy Transfer LP', domain: 'energytransfer.com' },
  { symbol: 'WES', name: 'Western Midstream Partners LP', domain: 'westernmidstream.com' },
  { symbol: 'DCP', name: 'DCP Midstream LP', domain: 'dcpmidstream.com' },
  { symbol: 'ENLC', name: 'EnLink Midstream LLC', domain: 'enlink.com' },
  { symbol: 'CEQP', name: 'Crestwood Equity Partners LP', domain: 'crestwoodlp.com' },
  { symbol: 'GEL', name: 'Genesis Energy LP', domain: 'genesisenergy.com' },
  { symbol: 'USAC', name: 'USA Compression Partners LP', domain: 'usacompression.com' },
  { symbol: 'HEP', name: 'Holly Energy Partners LP', domain: 'hollyenergy.com' },
  { symbol: 'SUN', name: 'Sunoco LP', domain: 'sunocolp.com' },
  { symbol: 'CAPL', name: 'CrossAmerica Partners LP', domain: 'crossamericapartners.com' },
  { symbol: 'DINO', name: 'HF Sinclair Corporation', domain: 'hfsinclair.com' },
  { symbol: 'ANDV', name: 'Andersons Inc', domain: 'andersonsinc.com' },
  { symbol: 'UAN', name: 'CVR Partners LP', domain: 'cvrpartners.com' },
  { symbol: 'CF', name: 'CF Industries Holdings Inc', domain: 'cfindustries.com' },
  { symbol: 'MOS', name: 'The Mosaic Company', domain: 'mosaicco.com' },
  { symbol: 'NTR', name: 'Nutrien Ltd', domain: 'nutrien.com' },
  { symbol: 'IPI', name: 'Intrepid Potash Inc', domain: 'intrepidpotash.com' },
  { symbol: 'SMG', name: 'The Scotts Miracle-Gro Company', domain: 'scotts.com' },
  { symbol: 'FMC', name: 'FMC Corporation', domain: 'fmc.com' },
  { symbol: 'CTVA', name: 'Corteva Inc', domain: 'corteva.com' },
  { symbol: 'AVTR', name: 'Avantor Inc', domain: 'avantorsciences.com' },
  { symbol: 'WLK', name: 'Westlake Corporation', domain: 'westlake.com' },
  { symbol: 'OLN', name: 'Olin Corporation', domain: 'olin.com' },
  { symbol: 'EMN', name: 'Eastman Chemical Company', domain: 'eastman.com' },
  { symbol: 'ASH', name: 'Ashland Global Holdings Inc', domain: 'ashland.com' },
  { symbol: 'HUN', name: 'Huntsman Corporation', domain: 'huntsman.com' },
  { symbol: 'ALB', name: 'Albemarle Corporation', domain: 'albemarle.com' },
  { symbol: 'SHW', name: 'The Sherwin-Williams Company', domain: 'sherwin-williams.com' },
  { symbol: 'RPM', name: 'RPM International Inc', domain: 'rpminc.com' },
  { symbol: 'AXTA', name: 'Axalta Coating Systems Ltd', domain: 'axalta.com' },
  { symbol: 'NEU', name: 'NewMarket Corporation', domain: 'newmarket.com' },
  { symbol: 'SXT', name: 'Sensient Technologies Corporation', domain: 'sensient.com' },
  { symbol: 'MLKN', name: 'MillerKnoll Inc', domain: 'millerknoll.com' },
  { symbol: 'HNI', name: 'HNI Corporation', domain: 'hnicorp.com' },
  { symbol: 'KNSL', name: 'Kinsale Capital Group Inc', domain: 'kinsalecapitalgroup.com' },
  { symbol: 'RLI', name: 'RLI Corp', domain: 'rlicorp.com' },
  { symbol: 'SIGI', name: 'Selective Insurance Group Inc', domain: 'selective.com' },
  { symbol: 'THG', name: 'The Hanover Insurance Group Inc', domain: 'hanover.com' },
  { symbol: 'ORI', name: 'Old Republic International Corp', domain: 'oldrepublic.com' },
  { symbol: 'KMPR', name: 'Kemper Corporation', domain: 'kemper.com' },
  { symbol: 'SAFT', name: 'Safety Insurance Group Inc', domain: 'safetyinsurance.com' },
  { symbol: 'UFCS', name: 'United Fire Group Inc', domain: 'unitedfiregroup.com' },
  { symbol: 'JRVR', name: 'James River Group Holdings Ltd', domain: 'jrgh.com' },
  { symbol: 'GLRE', name: 'Greenlight Capital Re Ltd', domain: 'greenlightre.ky' },
  { symbol: 'HALL', name: 'Hallmark Financial Services Inc', domain: 'hallmarkgrp.com' },
] as const;

export type Stock = typeof POPULAR_STOCKS[number];
